### ISSUE TITLE
Composer create project

### ISSUE THREAD

**Issue by moacode** [batchnz/craft-starter#10]
I went to create a new project using `composer create-project batchnz/craft-starter newproj` and I got the following error:

<img width="505" alt="Screen Shot 2020-09-16 at 10 34 38 AM" src="https://user-images.githubusercontent.com/5515179/93271883-6b30ab80-f808-11ea-8d3d-bdd449d8b098.png">

This happens when run within a container too (`fin rc composer create-project batchnz/craft-starter newproj`).

**Comment by judereid** [comment]
@thejoshsmith I've updated the readme and fixed up the command to use our correct Packagist, so this _should_ work now. 
Closing this one off.
